name: absensi_sdn_gubrih_1
description: "Aplikasi Presensi Wajah On-Device"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  tflite_flutter: ^0.12.0
  image: ^4.2.0
  path_provider: ^2.1.2
  light: ^4.0.0
  supabase_flutter: ^2.17.2
  path: ^1.9.1
  geolocator: ^14.0.3
  flutter_local_notifications: ^22.3.1
  wakelock_plus: ^1.7.0
  uuid: ^4.6.0
  permission_handler: ^11.3.1
  device_info_plus: ^13.2.0
  material3_expressive_loading_indicator: ^0.1.0
  battery_plus: ^6.0.0
  flutter_secure_storage: ^11.2.0
  timezone: ^0.11.1
  sqflite_sqlcipher: ^3.1.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/mobilefacenet.tflite
    - assets/models/pnet.tflite
    - assets/models/rnet.tflite
    - assets/models/onet.tflite
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#F2EDE4"
  image: assets/logo/icon.png
  android: true
  ios: false
  android_12:
    color: "#F2EDE4"
    image: assets/logo/icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo/icon.png"
  adaptive_icon_background: "#F2EDE4"
  adaptive_icon_foreground: "assets/logo/icon-big.png"